'use client';

// Adds an "Attach a file" control to the API playground's Body panel, with a
// content-type dropdown (application/json | multipart/form-data) right next to
// the file picker. The *regular* Send button does the sending:
//
//   • application/json    → the file is read as base64 into the operation's
//     base64 field and sent in the JSON body (small files; 10 MB JSON limit).
//   • multipart/form-data → the file is staged (see lib/staged-upload) and the
//     createAPIPage `onRequestInit` hook rewrites the request to multipart,
//     uploading the raw bytes (no size inflation, no JSON limit).
//
// There is no separate "Send file" button — the dropdown is the only control,
// and it changes how the next Send is encoded.
//
// Regeneration-safe: this lives in components/ (wired via createAPIPage in
// components/mdx.tsx), which `generate:openapi` never rewrites.
//
// Reusable: `createUploadBodyPanel([...configs])` takes one config per media
// operation — each names that operation's base64 field + multipart file part.
// The panel auto-detects which one applies on a page. Pair it with
// `createMultipartRewrite()` from lib/staged-upload in the same config.

import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import {
  Custom,
  DefaultCollapsiblePanel,
  type CollapsiblePanelProps,
} from 'fumadocs-openapi/playground/client';
import { stagedUpload, createMultipartRewrite } from '@/lib/staged-upload';

export interface UploadFieldConfig {
  /** JSON body field that holds the inline base64 (e.g. `mediaBase64`). */
  base64Field: string;
  /** Multipart part name the server reads the file from (e.g. `mediaFile`). */
  fileField: string;
}

type ContentType = 'application/json' | 'multipart/form-data';

// Files at/under this size are safe for the JSON path; express.json caps the
// body at 10 MB and base64 inflates ~33%.
const INLINE_SAFE_BYTES = 7 * 1024 * 1024;

function readAsDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(r.result as string);
    r.onerror = () => reject(r.error);
    r.readAsDataURL(file);
  });
}

// True when THIS operation renders an actual playground input for `<field>`.
// Fumadocs ids body controls `_body._<field>`, so this fires only on a real
// request *field* — never on a prose mention of the name, and (because callers
// re-evaluate it on every DOM mutation) it self-corrects to `false` once a page
// without that field has rendered, rather than latching on stale DOM left over
// from a client-side navigation.
function bodyFieldPresent(field: string): boolean {
  return !!document.querySelector(`[data-api-section="request"] [id="_body._${field}"]`);
}

// Re-evaluate `compute()` against the live DOM on mount and on every mutation,
// returning its current value. Unlike a one-shot observer that disconnects after
// the first hit, this keeps the result in sync with the DOM — so a control keyed
// off it disappears when its field does (e.g. after navigating to an operation
// that lacks it). `compute` is captured once; keep it self-contained.
function useDomSignal<T>(active: boolean, compute: () => T, initial: T): T {
  const [value, setValue] = useState<T>(initial);
  useEffect(() => {
    if (!active) return;
    const run = () => setValue(compute());
    run();
    const obs = new MutationObserver(run);
    obs.observe(document.body, { childList: true, subtree: true });
    return () => obs.disconnect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active]);
  return value;
}

// Fields to render BELOW the bottom-pinned array(s) on the send-in-chat body.
// Fumadocs sinks array/object fields to the end of the body grid with
// `order: 9999`; primitives default to `order: 0`, so they always land ABOVE
// the array. These niche correlation/typing knobs read better grouped at the
// very end, after `pollOptions` — so we push them past the array (see
// useTrailingBodyFields).
const TRAILING_SEND_IN_CHAT_FIELDS = ['secret', 'withTyping', 'typingSeconds'];
// The scheduled-messages body (POST /v1/scheduled-messages/{chatId}) has no
// typing knobs, but we still sink `secret` below the `pollOptions` array so its
// field layout matches send-message. Gated on `sendAt` presence, which uniquely
// identifies the scheduled body (the immediate send-in-chat body has no sendAt).
const TRAILING_SCHEDULED_FIELDS = ['secret'];
const TRAILING_ORDER = '10000'; // > fumadocs' array `order: 9999`

// Give the named body fields a CSS `order` greater than the array's 9999 so they
// render after it in the grid. The fields are auto-generated by fumadocs, so we
// reach them via their `_body._<field>` input and style the enclosing grid-item
// `fieldset`. Re-applied on every DOM mutation (fumadocs re-renders drop the
// inline style); `order` is an attribute change, not childList, so this never
// retriggers the observer.
function useTrailingBodyFields(active: boolean, fields: string[]): void {
  useEffect(() => {
    if (!active) return;
    const apply = () => {
      for (const f of fields) {
        const input = document.querySelector(
          `[data-api-section="request"] [id="_body._${f}"]`,
        );
        const cell = input?.closest('fieldset');
        if (cell) (cell as HTMLElement).style.order = TRAILING_ORDER;
      }
    };
    apply();
    const obs = new MutationObserver(apply);
    obs.observe(document.body, { childList: true, subtree: true });
    return () => obs.disconnect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active]);
}

// Render the stored ISO-8601 `sendAt` value as the `YYYY-MM-DDThh:mm` string a
// native `datetime-local` input expects, in the viewer's LOCAL timezone. Returns
// '' for an absent / unparseable value so the input shows empty.
function isoToLocalInput(iso: unknown): string {
  if (typeof iso !== 'string' || iso === '') return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;
}

// A native date+time picker for the `sendAt` body field. Mirrors the file-attach
// pattern: it doesn't replace the raw `sendAt` text input, it sits beside the
// body and *fills* that field. The picker reads wall-clock time in the viewer's
// local zone and writes the API's expected ISO-8601-with-offset string (UTC `Z`)
// via `setValue`. Clearing the input unsets the field (immediate send).
function SendAtControl() {
  const sendAt = Custom.useController(['body', 'sendAt']);

  // Hide the raw auto-generated `sendAt` text input — this picker is the
  // canonical control and binds the same `['body','sendAt']` field, so the
  // native input would be a redundant duplicate. Mirrors MessageTextControl's
  // treatment of the `text` field. Re-run on every mutation (fumadocs
  // re-renders the panel on the client).
  useEffect(() => {
    const hide = () => {
      document
        .querySelectorAll<HTMLElement>('[id="_body._sendAt"]')
        .forEach((el) => {
          const fieldset = el.closest('fieldset');
          if (fieldset) fieldset.style.display = 'none';
        });
    };
    hide();
    const obs = new MutationObserver(hide);
    obs.observe(document.body, { childList: true, subtree: true });
    return () => obs.disconnect();
  }, []);

  return (
    <div className="order-first col-span-full flex flex-col gap-2 rounded-lg border border-fd-border p-3">
      <span className="text-xs font-medium font-mono text-fd-foreground">Schedule send time</span>
      <div className="flex flex-wrap items-center gap-3">
        <input
          type="datetime-local"
          value={isoToLocalInput(sendAt.value)}
          onChange={(e) => {
            const v = e.target.value;
            if (!v) {
              sendAt.setValue(undefined);
              return;
            }
            const d = new Date(v);
            sendAt.setValue(Number.isNaN(d.getTime()) ? undefined : d.toISOString());
          }}
          className="rounded-md border border-fd-border bg-fd-background px-2 py-1 text-sm text-fd-foreground [color-scheme:light] dark:[color-scheme:dark]"
        />
        {typeof sendAt.value === 'string' && sendAt.value ? (
          <span className="text-xs text-fd-muted-foreground font-mono">
            sendAt = {sendAt.value}
          </span>
        ) : (
          <span className="text-xs text-fd-muted-foreground">
            Pick a local date &amp; time. Leave empty to send immediately.
          </span>
        )}
      </div>
    </div>
  );
}

// Common WhatsApp reaction emojis. The native text input stays the source of
// truth (any emoji is valid); this grid just *fills* it with one click for the
// usual cases, mirroring the SendAtControl pattern.
const REACTION_EMOJIS = [
  '👍', '❤️', '😂', '😮', '😢', '🙏', '🔥', '🎉',
  '👏', '✅', '💯', '🥳', '😍', '😡', '🤔', '🙌',
];

// An emoji picker for the `emoji` body field of the react-to-message operation.
// Like SendAtControl, it sits beside the raw `emoji` input and writes into it via
// `setValue` rather than replacing it. "Clear" sets an empty string, which the
// endpoint treats as "remove your reaction".
function EmojiControl() {
  const emoji = Custom.useController(['body', 'emoji']);
  const current = typeof emoji.value === 'string' ? emoji.value : '';

  return (
    <div className="col-span-full flex flex-col gap-2 rounded-lg border border-fd-border p-3">
      <span className="text-xs font-medium font-mono text-fd-foreground">Pick a reaction emoji</span>
      <div className="flex flex-wrap items-center gap-1.5">
        {REACTION_EMOJIS.map((e) => {
          const selected = current === e;
          return (
            <button
              key={e}
              type="button"
              aria-pressed={selected}
              title={`React with ${e}`}
              onClick={() => emoji.setValue(e)}
              className={`rounded-md border px-2 py-1 text-lg leading-none transition-colors ${
                selected
                  ? 'border-fd-primary bg-fd-primary/10'
                  : 'border-fd-border bg-fd-background hover:bg-fd-accent'
              }`}
            >
              {e}
            </button>
          );
        })}
        <button
          type="button"
          title="Remove your reaction (sends an empty emoji)"
          onClick={() => emoji.setValue('')}
          className="rounded-md border border-fd-border bg-fd-background px-2 py-1 text-xs text-fd-muted-foreground hover:bg-fd-accent"
        >
          Clear
        </button>
      </div>
      {current ? (
        <span className="text-xs text-fd-muted-foreground font-mono">emoji = {current}</span>
      ) : (
        <span className="text-xs text-fd-muted-foreground">
          Pick an emoji to fill the field. Leave empty to remove your reaction.
        </span>
      )}
    </div>
  );
}

// Replace fumadocs's default single-line `text` input with a multiline
// <textarea>. fumadocs renders every scalar string field as a one-line <input>
// (no per-field renderer hook from this RSC setup), and an <input> normalizes
// away newlines — so we can't just widen it; we bind a real textarea to the
// same body field through the data engine (newlines preserved) and hide the
// native input row. Like Emoji/SendAt this is gated on the field being present.
function MessageTextControl() {
  const text = Custom.useController(['body', 'text']);
  const value = typeof text.value === 'string' ? text.value : '';

  // Hide the native `text` fieldset while this control is mounted. Both bind the
  // same `['body','text']` field via the shared engine, so the value stays in
  // sync; the native input just becomes a hidden, redundant duplicate. Re-run on
  // every mutation since fumadocs re-renders the panel on the client.
  useEffect(() => {
    const hide = () => {
      document
        .querySelectorAll<HTMLElement>('[id="_body._text"]')
        .forEach((el) => {
          const fieldset = el.closest('fieldset');
          if (fieldset) fieldset.style.display = 'none';
        });
    };
    hide();
    const obs = new MutationObserver(hide);
    obs.observe(document.body, { childList: true, subtree: true });
    return () => obs.disconnect();
  }, []);

  return (
    <div className="order-first col-span-full flex flex-col gap-2 rounded-lg border border-fd-border p-3">
      <span className="text-xs font-medium font-mono text-fd-foreground">
        text <span className="text-red-400/80">*</span>
      </span>
      <textarea
        value={value}
        rows={5}
        placeholder="Type your message — line breaks are preserved."
        onChange={(e) => text.setValue(e.target.value)}
        className="w-full min-h-[120px] resize-y rounded-md border border-fd-border bg-fd-secondary px-2 py-1.5 text-[0.8125rem] text-fd-secondary-foreground transition-colors placeholder:text-fd-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-fd-ring"
      />
    </div>
  );
}

function UploadControls({ config }: { config: UploadFieldConfig }) {
  const base64 = Custom.useController(['body', config.base64Field]);
  const [ct, setCt] = useState<ContentType>('application/json');
  const [status, setStatus] = useState<string | null>(null);
  const [file, setFile] = useState<File | null>(null);

  // Drop any staged file when the user navigates away.
  useEffect(() => () => stagedUpload.clear(), []);

  const apply = async (f: File | null, mode: ContentType) => {
    if (!f) {
      stagedUpload.clear();
      base64.setValue('');
      setStatus(null);
      return;
    }
    if (mode === 'multipart/form-data') {
      // Stage for the onRequestInit rewrite; don't also carry base64 in JSON.
      stagedUpload.set({
        file: f,
        fileField: config.fileField,
        excludeFields: [config.base64Field, config.fileField],
      });
      base64.setValue('');
      setStatus(`"${f.name}" will upload as multipart/form-data when you press Send.`);
      return;
    }
    // application/json → inline base64
    stagedUpload.clear();
    if (f.size > INLINE_SAFE_BYTES) {
      base64.setValue('');
      setStatus(
        `⚠ ${(f.size / 1048576).toFixed(1)} MB is too large for application/json (10 MB body limit). Switch to multipart/form-data.`,
      );
      return;
    }
    base64.setValue(await readAsDataUrl(f));
    setStatus(`"${f.name}" → ${config.base64Field} set. Press Send.`);
  };

  return (
    <div className="order-first col-span-full flex flex-col gap-2 rounded-lg border border-fd-border p-3">
      <span className="text-xs font-medium font-mono text-fd-foreground">Attach a file</span>
      <div className="flex flex-wrap items-center gap-3">
        <input
          type="file"
          className="text-sm text-fd-muted-foreground file:me-3 file:rounded-md file:border file:border-fd-border file:bg-fd-secondary file:px-3 file:py-1.5 file:text-fd-secondary-foreground file:text-sm hover:file:bg-fd-accent"
          onChange={(e) => {
            const f = e.target.files?.[0] ?? null;
            setFile(f);
            void apply(f, ct);
          }}
        />
        <label className="flex items-center gap-1.5 text-sm text-fd-muted-foreground">
          Send as
          <select
            value={ct}
            onChange={(e) => {
              const next = e.target.value as ContentType;
              setCt(next);
              void apply(file, next);
            }}
            className="rounded-md border border-fd-border bg-fd-background px-2 py-1 text-sm text-fd-foreground"
          >
            <option value="application/json">application/json (base64)</option>
            <option value="multipart/form-data">multipart/form-data (file)</option>
          </select>
        </label>
      </div>
      {status ? <span className="text-xs text-fd-muted-foreground">{status}</span> : null}
    </div>
  );
}

/**
 * Build the playground CollapsiblePanel override. On a Body panel it picks the
 * first config whose `base64Field` has an actual input on the page and renders
 * the file controls for it; if none match (non-media operation) it's the default
 * panel. It also renders the emoji and schedule-send controls when those body
 * fields are present.
 */
export function createUploadBodyPanel(configs: UploadFieldConfig[]) {
  return function UploadBodyPanel(props: CollapsiblePanelProps) {
    const isBody = props['data-type'] === 'body';
    // Path parameters are always required to address the resource, so open
    // that panel on mount. We set Radix's `defaultOpen` rather than relying on
    // <ApiAutoExpand>'s synthetic click — the click races hydration on the
    // playground triggers, so it's not reliable for the panels. The panel
    // stays collapsible (chevron intact); this only changes the initial state.
    const isPath = props['data-type'] === 'path';

    // All three controls are keyed off the *actual* playground body inputs
    // (`_body._<field>`), not page text. Text matching false-triggered: the
    // upload panel latched onto a `mediaBase64` mention left in the DOM during a
    // client-side navigation and showed "Attach a file" on operations (e.g.
    // react-to-message) that have no media field at all. Field presence is exact
    // and self-correcting — the control disappears as soon as a page without
    // that field renders.
    const active = useDomSignal(
      isBody,
      () => configs.find((c) => bodyFieldPresent(c.base64Field)) ?? null,
      null as UploadFieldConfig | null,
    );
    const hasSendAt = useDomSignal(isBody, () => bodyFieldPresent('sendAt'), false);
    const hasEmoji = useDomSignal(isBody, () => bodyFieldPresent('emoji'), false);
    const hasText = useDomSignal(isBody, () => bodyFieldPresent('text'), false);
    // `withTyping` is unique to the immediate send-in-chat body, so gating on it
    // pushes the trailing fields below `pollOptions` there WITHOUT touching the
    // scheduled-messages body (which shares `secret` but has no typing knobs).
    const hasWithTyping = useDomSignal(isBody, () => bodyFieldPresent('withTyping'), false);
    useTrailingBodyFields(isBody && hasWithTyping, TRAILING_SEND_IN_CHAT_FIELDS);
    // Scheduled body: push `secret` past `pollOptions` too (gated on sendAt).
    useTrailingBodyFields(isBody && hasSendAt, TRAILING_SCHEDULED_FIELDS);

    // The body object renders as one fieldset whose *label* is the "Open JSON
    // Editor" button and whose body is the `ObjectInput` field grid. To keep
    // that button on top yet still float our text/file controls above the
    // auto-generated fields, we portal them *into* that grid (with `order-first`)
    // rather than rendering them as panel siblings. Locate the grid via the
    // button so it works on any object body (e.g. group-picture has no `text`).
    const bodyGrid = useDomSignal<HTMLElement | null>(
      isBody,
      () => {
        const button = Array.from(
          document.querySelectorAll<HTMLElement>(
            '[data-api-section="request"] button',
          ),
        ).find((b) => b.textContent?.trim() === 'Open JSON Editor');
        return (
          (button
            ?.closest('fieldset')
            ?.querySelector(':scope > div.grid') as HTMLElement) ?? null
        );
      },
      null,
    );

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const Default = DefaultCollapsiblePanel as any;
    return (
      <Default {...props} defaultOpen={props.defaultOpen ?? isPath}>
        {props.children}
        {/* Float the text + file-attach controls to the top of the field grid
            (via `order-first`), directly under the "Open JSON Editor" button,
            by portaling them into the body object's grid. */}
        {isBody && bodyGrid && (hasText || active || hasSendAt)
          ? createPortal(
              <>
                {/* SendAt picker first so the "Schedule send time" control sits
                    at the very top of the body panel, above the text field. */}
                {hasSendAt ? <SendAtControl /> : null}
                {hasText ? <MessageTextControl /> : null}
                {active ? <UploadControls config={active} /> : null}
              </>,
              bodyGrid,
            )
          : null}
        {isBody && hasEmoji ? <EmojiControl /> : null}
      </Default>
    );
  };
}

// Pre-bound for this API. The factories are bound here — inside the client
// module — because a server module (components/mdx.tsx) cannot invoke a client
// function. One config per media operation:
//   • POST /v1/messages/{chat_id}  — mediaBase64 / mediaFile
//   • PUT  /v1/groups/{id}/picture — file_data_url / file
// Add a new operation by appending its { base64Field, fileField } here.
export const PlaygroundBodyPanel = createUploadBodyPanel([
  { base64Field: 'mediaBase64', fileField: 'mediaFile' },
  { base64Field: 'file_data_url', fileField: 'file' },
]);
export const playgroundMultipartRewrite = createMultipartRewrite();
